setup/urls.py
from django.contrib import admin
from django.urls import path
from keystore.views import (
    KvstoreListView,
    KvstoreCreateView,
    KvstoreUpdateView,
    KvstoreDeleteView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", KvstoreListView.as_view(), name="kvstore_list"),
    path("create", KvstoreCreateView.as_view(), name="kvstore_create"),
    path("update/<int:pk>", KvstoreUpdateView.as_view(), name="kvstore_update"),
    path("delete/<int:pk>", KvstoreDeleteView.as_view(), name="kvstore_delete"),
]

keystore/models.py
from django.db import models


# Create your models here.
class Keystore(models.Model):
    key = models.CharField(max_length=100, unique=True)
    value = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    client_ip = models.GenericIPAddressField(null=True, blank=True)

    def __str__(self):
        return f"{self.key} = {self.value}"

keystore/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Keystore


class KvstoreListView(ListView):
    model = Keystore
    template_name = "kvstore_list.html"


class CaptureClientIPMixin:
    def form_valid(self, form):
        x_forwarded_for = self.request.META.get("HTTP_X_FORWARDED_FOR")
        if x_forwarded_for:
            ip = x_forwarded_for.split(",")[0]
        else:
            ip = self.request.META.get("REMOTE_ADDR")

        form.instance.client_ip = ip

        return super().form_valid(form)


class KvstoreCreateView(CaptureClientIPMixin, CreateView):
    model = Keystore
    template_name = "kvstore_form.html"
    fields = ["key", "value"]
    success_url = reverse_lazy("kvstore_list")


class KvstoreUpdateView(CaptureClientIPMixin, UpdateView):
    model = Keystore
    fields = ["key", "value"]
    template_name = "kvstore_form.html"
    success_url = reverse_lazy("kvstore_list")


class KvstoreDeleteView(DeleteView):
    model = Keystore
    template_name = "kvstore_confirm_delete.html"
    success_url = reverse_lazy("kvstore_list")

keystore/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Website - Keyvalue Store</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar bg-dark">
    <div class="container">
      <a href="{% url 'kvstore_list' %}" style="text-decoration: none;">
        <h1 class="navbar-text text-white">
          KeyValueStore
        </h1>
      </a>
    </div>
  </nav>
  <main class="container mt-3">{% block content %}{% endblock content %}</main>
</body>
</html>

keystore/templates/kvstore_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Item</h1>
  <p>Are you sure you want to delete the item?</p>
  <strong>Key:</strong> <span>{{ keystore.key }}</span><br>
  <strong>Value:</strong> <span>{{ keystore.value }}</span><br>
  <strong>Created At:</strong> <span>{{ keystore.created_at }}</span><br>
  <strong>Last Update At:</strong> <span>{{ keystore.updated_at }}</span> <br>
  <strong>By:</strong> <span>{{ keystore.client_ip }}</span> 

  <form method="POST" class="mt-3">
    {% csrf_token %}
    <a href="{% url 'kvstore_list' %}" class="btn btn-secondary">Cancel</a>
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>

{% endblock content %}

keystore/templates/kvstore_form.html
{% extends "base.html" %}
{% load crispy_forms_tags  %}

{% block content %}
  {% if keystore.pk %}
    <h2 class="mb-3">Update KeyValue Item</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form| crispy }}
      <button type="submit" class="btn btn-dark">Update Item</button>
    </form>
  {% else %}
    <h2 class="mb-3">New KeyValue Item</h2>
    <form method="POST">
      {% csrf_token %}
      {{ form| crispy }}
      <button type="submit" class="btn btn-dark">Create Item</button>
    </form>
  {% endif %}
  
{% endblock content %}

keystore/templates/kvstore_list.html
{% extends "base.html" %}

{% block content %}
  <h2 class="mb-3">KeyValue List</h2>
  {% if keystore_list %}
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Key</th>
          <th scope="col">Value</th>
          <th scope="col">Created At</th>
          <th scope="col">Last Updated At</th>
          <th scope="col">IP Address</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for item in keystore_list %}
          <tr class="fw-light">
            <td scope="row">{{item.key}}</td>
            <td>{{item.value}}</td>
            <td>{{item.created_at}}</td>
            <td>{{item.updated_at|default:"-"}}</td>
            <td>{{item.client_ip}}</td>
            <td>
              <a href="{% url 'kvstore_update' pk=item.pk%}" class="btn btn-secondary btn-sm">Edit</a>
              <a href="{% url 'kvstore_delete' pk=item.pk%}" class="btn btn-danger btn-sm">Delete</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No data <p>
  {% endif %}
  <a href="{% url 'kvstore_create' %}" class="btn btn-primary">New Item</a>
{% endblock content %}